export const techQA = [
  { id: 1, hint: "Structure of a web page", answer: "HTML" },
  { id: 2, hint: "Styles web pages", answer: "CSS" },
  { id: 3, hint: "Adds interactivity to websites", answer: "JavaScript" },
  { id: 4, hint: "Runs when condition is true", answer: "if" },
  { id: 5, hint: "Runs if condition is false", answer: "else" },
  { id: 6, hint: "Repeats code while condition is true", answer: "while" },
  { id: 7, hint: "Loop that runs fixed number of times", answer: "for" },
  { id: 8, hint: "Stops a loop immediately", answer: "break" },
  { id: 9, hint: "Skips current loop iteration", answer: "continue" },
  { id: 10, hint: "Prints message to console", answer: "console.log" },

  { id: 11, hint: "Declares a variable in JavaScript", answer: "let" },
  { id: 12, hint: "Declares a constant", answer: "const" },
  { id: 13, hint: "Declares a function", answer: "function" },
  { id: 14, hint: "Compares equality in programming", answer: "==" },
  { id: 15, hint: "Strict equality comparison", answer: "===" },
  { id: 16, hint: "Means not equal", answer: "!=" },
  { id: 17, hint: "Logical AND operator", answer: "&&" },
  { id: 18, hint: "Logical OR operator", answer: "||" },
  { id: 19, hint: "Logical NOT operator", answer: "!" },
  { id: 20, hint: "Access object property", answer: "dot operator" },

  { id: 21, hint: "Creates hyperlink in HTML", answer: "anchor element" },
  { id: 22, hint: "Displays image in HTML", answer: "image element" },
  { id: 23, hint: "Creates paragraph", answer: "paragraph element" },
  { id: 24, hint: "Largest HTML heading", answer: "heading level one" },
  { id: 25, hint: "Creates a button", answer: "button element" },
  { id: 26, hint: "Creates unordered list", answer: "unordered list element" },
  { id: 27, hint: "Creates ordered list", answer: "ordered list element" },
  { id: 28, hint: "Creates list item", answer: "list item element" },
  { id: 29, hint: "HTML container for scripts", answer: "script element" },
  { id: 30, hint: "Contains webpage metadata", answer: "head element" },

  { id: 31, hint: "Main visible part of webpage", answer: "body element" },
  { id: 32, hint: "Links CSS file", answer: "link element" },
  { id: 33, hint: "Links external JavaScript", answer: "src attribute" },
  { id: 34, hint: "Links CSS file location", answer: "href attribute" },
  { id: 35, hint: "Changes text color", answer: "color property" },
  {
    id: 36,
    hint: "Changes background color",
    answer: "background color property",
  },
  { id: 37, hint: "Controls text size", answer: "font size property" },
  { id: 38, hint: "Adds space inside element", answer: "padding property" },
  { id: 39, hint: "Adds space outside element", answer: "margin property" },
  { id: 40, hint: "Makes text bold", answer: "font weight property" },

  { id: 41, hint: "Centers text in CSS", answer: "text align property" },
  { id: 42, hint: "Value used to center text", answer: "center value" },
  { id: 43, hint: "Rounds element corners", answer: "border radius property" },
  { id: 44, hint: "Adds shadow to element", answer: "box shadow property" },
  { id: 45, hint: "Adds border to element", answer: "border property" },
  { id: 46, hint: "Controls element width", answer: "width property" },
  { id: 47, hint: "Controls element height", answer: "height property" },
  { id: 48, hint: "Hides an element", answer: "display none value" },
  { id: 49, hint: "Enables flex layout", answer: "display flex value" },
  { id: 50, hint: "Enables grid layout", answer: "display grid value" },

  { id: 51, hint: "One dimensional layout system", answer: "flexbox" },
  { id: 52, hint: "Two dimensional layout system", answer: "grid layout" },
  { id: 53, hint: "Triggered when element is clicked", answer: "click event" },
  { id: 54, hint: "Triggered when page loads", answer: "load event" },
  { id: 55, hint: "Stores temporary data in computer", answer: "RAM" },
  { id: 56, hint: "Brain of the computer", answer: "CPU" },
  { id: 57, hint: "Displays visual output", answer: "monitor" },
  { id: 58, hint: "Used to type text", answer: "keyboard" },
  { id: 59, hint: "Used to move cursor", answer: "mouse" },
  { id: 60, hint: "Permanent storage device", answer: "hard drive" },

  { id: 61, hint: "Portable storage device", answer: "flash drive" },
  { id: 62, hint: "Online file storage", answer: "cloud storage" },
  { id: 63, hint: "Tracks code versions", answer: "Git" },
  { id: 64, hint: "Hosts Git repositories", answer: "GitHub" },
  { id: 65, hint: "Uploads code to repository", answer: "git push command" },
  { id: 66, hint: "Downloads repository copy", answer: "git clone command" },
  { id: 67, hint: "Saves changes in Git", answer: "git commit command" },
  { id: 68, hint: "Default branch name", answer: "main branch" },
  { id: 69, hint: "Creates copy of repository", answer: "fork repository" },
  { id: 70, hint: "Protocol for web pages", answer: "HTTP" },

  { id: 71, hint: "Secure web protocol", answer: "HTTPS" },
  { id: 72, hint: "Language for database queries", answer: "SQL" },
  { id: 73, hint: "Popular relational database", answer: "MySQL" },
  { id: 74, hint: "Popular NoSQL database", answer: "MongoDB" },
  { id: 75, hint: "Popular language for AI", answer: "Python" },
  { id: 76, hint: "Language for Android apps", answer: "Kotlin" },
  { id: 77, hint: "Language for iOS apps", answer: "Swift" },
  { id: 78, hint: "Company that created Windows", answer: "Microsoft" },
  { id: 79, hint: "Company that created iPhone", answer: "Apple" },
  { id: 80, hint: "Company that created Android", answer: "Google" },

  { id: 81, hint: "Web browser by Google", answer: "Chrome" },
  { id: 82, hint: "Web browser by Mozilla", answer: "Firefox" },
  { id: 83, hint: "Programming language inside browser", answer: "JavaScript" },
  {
    id: 84,
    hint: "Symbol that starts HTML tag",
    answer: "opening angle bracket &gt;",
  },
  {
    id: 85,
    hint: "Symbol that ends HTML &tg;",
    answer: "closing angle bracket &lt;",
  },
  {
    id: 86,
    hint: "Single line comment in JavaScript",
    answer: "double slash comment",
  },
  { id: 87, hint: "Multi line comment start", answer: "slash star comment" },
  { id: 88, hint: "Statement that checks condition", answer: "if statement" },
  { id: 89, hint: "Returns value from function", answer: "return statement" },
  { id: 90, hint: "Creates table in HTML", answer: "table element" },
];
